PS-1.c: PS-1.c File Reference
PS-1.c File Reference
brief explanation of PS-1.c from xn
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <time.h>
Classes
struct queue
to store unused roll numbers
struct node
node to encapsulate individual student's data
Macros
#define MAX 13
Typedefs
typedef struct queue queue
to store unused roll numbers
typedef struct node node
node to encapsulate individual student's data
Functions
void insert (int roll, char *name, char *dob, char *addr, char *phno)
to insert the new data inyto doubly linked list
node * newNode (int roll, char *name, char *dob, char *addr, char *phno)
to initialize each node
void delete (int roll, queue *q)
to delete the node corresponding to given roll number
void search (int n)
to search for student having given roll number
void modify (int roll)
modify the information
void printList ()
to print the list of students
void sortByName ()
sort the list according to aphabetical order
void sortByRollNumber ()
sort the list according to roll number
void swap_int (int *r1, int *r2)
helper function to swap two integers
queue * init_queue (queue *q)
initialize the queue to store unused roll number
void push (queue *q, int n)
insert the unused roll number in queue
int pop (queue *q)
get the unused roll number to use
bool search_queue (queue *q, int n)
helper function to to search whether given roll number is used or unused
void main ()
this main func @ return nothing
Variables
node * first = NULL
node * last = NULL
int size = 0
Detailed Description
brief explanation of PS-1.c from xn
Author
karanpreet Singh
Definition in file PS-1.c.
Macro Definition Documentation
MAX
#define MAX 13
Definition at line 12 of file PS-1.c.
Typedef Documentation
queue
typedef struct queue queue
to store unused roll numbers
node
typedef struct node node
node to encapsulate individual student's data
Function Documentation
insert()
void insert (int roll, char * name, char * dob, char * addr, char * phno)
to insert the new data inyto doubly linked list
Definition at line 268 of file PS-1.c.
{
     node *nNode = newNode(roll, name,dob,addr,phno);
     if (first == last && first == NULL)
     {
        first = last = nNode;
        first->next = last->next = NULL;
        first->prev = last->prev = NULL;
        while ((getchar()) != '\n');
     }
     else
     {
        last->next = nNode;
        nNode->prev = last;
        last = nNode;
        last->next = first;
        first->prev = last;
        sortByRollNumber();
        while ((getchar()) != '\n');
     }
 }
References node::addr, node::dob, first, last, node::name, newNode(), node::next, node::phno, node::prev, node::roll, and sortByRollNumber().
Referenced by main().
newNode()
node * newNode (int roll, char * name, char * dob, char * addr, char * phno)
to initialize each node
Definition at line 256 of file PS-1.c.
{
    node* one_node = (node*)(malloc(sizeof(node)));
    one_node->roll=roll;
    strcpy(one_node->name,nome);
    strcpy(one_node->dob,dobt);
    strcpy(one_node->addr,adr);
    strcpy(one_node->phno,phnu);
    one_node->next = one_node;
    one_node->prev = one_node;
    return one_node;
 }
References node::addr, node::dob, node::name, node::next, node::phno, node::prev, and node::roll.
Referenced by insert().
delete()
void delete (int roll, queue * q)
to delete the node corresponding to given roll number
Definition at line 289 of file PS-1.c.
{
    node *current;
    node *prev;
    prev = first;
    current= first->next;
    bool b=false;
    do {
        if(current->roll == roll)
        {
            b=true;
            break;
        }
        current=current->next;
        prev=prev->next;
     } while(current!=first->next);
     if(b&&current!=first){
        prev->next=current->next;
        current->next->prev=prev;
        current->next=NULL;
        current->prev=NULL;
        push(q,roll);
    }
    else if(current==first){
        first=first->next;
        last->next=first;
        first->prev=last;
    }
    else printf("Roll is still unused\n");
 }
References first, last, node::next, node::prev, push(), and node::roll.
search()
void search (int n)
to search for student having given roll number
Definition at line 319 of file PS-1.c.
                   {
   node *current;
   current = first;
   bool b=false;
    do {
        int p = current->roll;
        if(p==n){
            b= true;
            break;
        }
        current=current->next;
    }while(current!=first);
    if(b){
        printf("salad");
         printf("name:%s\n",current->name);
         printf("address:%s\n",current->addr);
         printf("dob:%s\n",current->dob);
         printf("phone no:%s\n", current->phno);
    }
    else printf("student with roll number does not exist");
 }
References node::addr, node::dob, first, node::name, node::next, node::phno, and node::roll.
Referenced by main().
modify()
void modify (int roll)
modify the information
Definition at line 341 of file PS-1.c.
                      {
     node *current;
     current = first;
     bool b=false;
     do {
         if(current->roll == roll)
         {
             b=true;
             break;
         }
         current=current->next;
     }while(current!=first);
     if(b){
         printf("enter  name\n");
         scanf("%[^\n]s",current->name);
         while ((getchar()) != '\n');
         printf("enter  phone number\n");
         scanf("%s",current->phno);
         while ((getchar()) != '\n');
         printf("enter  address\n");
         scanf("%[^\n]s",current->addr);
         while ((getchar()) != '\n');
         printf("enter dob\n");
         scanf("%s",current->dob);
         while ((getchar()) != '\n');
     }
     else printf("roll number is still unused");
 }
References node::addr, node::dob, first, node::name, node::next, node::phno, and node::roll.
Referenced by main().
printList()
void printList ()
to print the list of students
Definition at line 411 of file PS-1.c.
                 {
     node *current;
     current =first;
     do{
         printf("roll no:%d\n",current->roll);
         printf("name:%s\n",current->name);
         printf("address:%s\n",current->addr);
         printf("dob:%s\n",current->dob);
         printf("phone no:%s\n", current->phno);
         current=current->next;
     }while(current!=first&&first->next!=NULL);
      if(first!=last)
      sortByRollNumber();
 }
References node::addr, node::dob, first, last, node::name, node::next, node::phno, node::roll, and sortByRollNumber().
Referenced by main().
sortByName()
void sortByName ()
sort the list according to aphabetical order
Definition at line 370 of file PS-1.c.
                  {
     int swapped, i;
     struct node *ptr1;
     struct node *lptr = first;
     if (first == NULL)
         return;
     do
     {
         swapped = 0;
         ptr1 = first;
         while (ptr1->next != lptr)
         {
             char* n1=ptr1->name;
             char* n2=ptr1->next->name;
             if (strcmp(n1,n2)>0)
             {
                 swap_int(&(ptr1->roll), &(ptr1->next->roll));
                 char temp[128];
                 char temp2[1024];
                 char temp3[20];
                 strncpy(temp,ptr1->name,128);
                 strncpy(ptr1->name,ptr1->next->name,128);
                 strncpy(ptr1->next->name,temp,128);
                 strncpy(temp2,ptr1->addr,1024);
                 strncpy(ptr1->addr,ptr1->next->addr,1024);
                 strncpy(ptr1->next->addr,temp2,1024);
                 strncpy(temp,ptr1->dob,128);
                 strncpy(ptr1->dob,ptr1->next->dob,128);
                 strncpy(ptr1->next->dob,temp,128);
                 strncpy(temp,ptr1->phno,20);
                 strncpy(ptr1->phno,ptr1->next->phno,20);
                 strncpy(ptr1->next->phno,temp,20);
                 swapped = 1;
             }
             ptr1 = ptr1->next;
         }
         lptr = ptr1;
     }
     while (swapped);
 }
References node::addr, node::dob, first, node::name, node::next, node::phno, node::roll, and swap_int().
Referenced by main().
sortByRollNumber()
void sortByRollNumber ()
sort the list according to roll number
Definition at line 426 of file PS-1.c.
{
     int swapped, i;
      node *ptr1;
      node *lptr = first;
     if (first == NULL)
         return;
     do
     {
         swapped = 0;
         ptr1 = first;
         while (ptr1->next != lptr)
         {
             if ((ptr1->roll > ptr1->next->roll))
             {
                 swap_int(&(ptr1->roll), &(ptr1->next->roll));
                 char temp[128];
                 char temp2[1024];
                 char temp3[20];
                 strncpy(temp,ptr1->name,128);
                 strncpy(ptr1->name,ptr1->next->name,128);
                 strncpy(ptr1->next->name,temp,128);
                 strncpy(temp2,ptr1->addr,1024);
                 strncpy(ptr1->addr,ptr1->next->addr,1024);
                 strncpy(ptr1->next->addr,temp2,1024);
                 strncpy(temp,ptr1->dob,128);
                 strncpy(ptr1->dob,ptr1->next->dob,128);
                 strncpy(ptr1->next->dob,temp,128);
                 strncpy(temp,ptr1->phno,20);
                 strncpy(ptr1->phno,ptr1->next->phno,20);
                 strncpy(ptr1->next->phno,temp,20);
                 swapped = 1;
             }
             ptr1 = ptr1->next;
         }
         lptr = ptr1;
     }
     while (swapped);
 }
References node::addr, node::dob, first, node::name, node::next, node::phno, node::roll, and swap_int().
Referenced by insert(), and printList().
swap_int()
void swap_int (int * r1, int * r2)
helper function to swap two integers
Definition at line 465 of file PS-1.c.
{
     int temp=*r1;
     *r1=*r2;
     *r2=temp;
 }
Referenced by sortByName(), and sortByRollNumber().
init_queue()
queue * init_queue (queue * q)
initialize the queue to store unused roll number
Definition at line 74 of file PS-1.c.
{
     q->rear=-1;
     q->front=-1;
     q->size=0;
     return q;
 }
References queue::front, queue::rear, and queue::size.
Referenced by main().
push()
void push (queue * q, int n)
insert the unused roll number in queue
Definition at line 81 of file PS-1.c.
{
     if(q->rear==-1&&q->front==-1){
         q->arr[0]=n;
         q->front=q->rear=0;
         q->size++;
     }
     else
     {
         q->arr[++q->rear]=n;
         q->size++;
     }
 }
References queue::arr, queue::front, queue::rear, and queue::size.
Referenced by delete(), and main().
pop()
int pop (queue * q)
get the unused roll number to use
Definition at line 94 of file PS-1.c.
                  {
     if(q->rear==-1&&q->front==-1)
         return -1;
     else if(q->size==1) {
         q->rear=-1;
         q->front=-1;
         return q->arr[0];
     }
     else {
         int num = q->arr[0];
         for(int i=1;i<q->size;i++)
             q->arr[i-1]=q->arr[i];
         q->size--;
         q->rear--;
         return num;
     }
 }
References queue::arr, queue::front, queue::rear, and queue::size.
Referenced by main().
search_queue()
bool search_queue (queue * q, int n)
helper function to to search whether given roll number is used or unused
Definition at line 112 of file PS-1.c.
{
     for(int i=0;i<size;i++){
         if(q->arr[i]==n)
           return true;
     }
     return false;
 }
References queue::arr, and size.
main()
void main ()
this main func @ return nothing
declare the queue
declare doubly linked list
choice for operation in switch menu
taking pointer to file
storing name for 13 students
storing address for 13 students
storing date of birth for 13 students
storing phone number for 13 students
buffer for getting individual line of the opened file
skip the first line
get each line until reaches end of file
get first element of each line
to mark start and end of cpu clock
store the time taken by cpu to perform operation
delete the data from the list
search for student with given roll number
modify the current values of data inside the node
sort the list in dictionary order
print the list
Definition at line 125 of file PS-1.c.
             {
     queue unusedRoll;
     init_queue(&unusedRoll);
     for(int i=0;i<13;i++)
         push(&unusedRoll,101+i);
     node students;
     int op;
     FILE *stream = fopen("StudentData.csv", "r");
     char **name_data = (char**)malloc(13 * sizeof(char*));
     char **address =(char**)malloc(13 * sizeof(char*));
     char **dtob = (char**)malloc(13 * sizeof(char*));
     char **phone = (char**)malloc(13 * sizeof(char*));
     char *line = (char*)malloc(1024 * sizeof(char));
     int i=0;
     fgets(line, 1024, stream);
     char* token=strtok(line, ",");
     token=strtok(NULL,"\n");
         while (fgets(line, 1024, stream))
         {
             token =  strtok(line, ",");
             token = strtok(NULL, ",");
             name_data[i]=(char*)malloc(strlen(token)*sizeof(char));
             strcpy(name_data[i],token);
             token = strtok(NULL, ",");
             dtob[i]=(char*)malloc(strlen(token)*sizeof(char));
             strcpy(dtob[i],token);
             token = strtok(NULL, "\"");
             address[i]=(char*)malloc(strlen(token)*sizeof(char));
             strcpy(address[i],token);
             token = strtok(NULL, ",[^\n");
             phone[i]=(char*)malloc(strlen(token)*sizeof(char));
             strcpy(phone[i],token);
             printf("%s\n",phone[i]);
             i++;
         }
     clock_t start, end;
     double cpu_time;
     while (1) {
         printf("\n\n1.Insert\n2.Delete\n3.Search\n4.modify\n5.sort\n6.PrintList\n\nEnter ur choice");
         printf("\nenter -1 to exit\n");
         scanf("%d",&op);
         while ((getchar()) != '\n');
         switch(op){
             case 1: // ! insert the student's data into the list
                     printf("operation insert\n");
                     printf("Enter number  for the student you want to insert\n");
                     int num;
                     int rollnum;
                     scanf("%d",&num);
                     while ((getchar()) != '\n');
                     start = clock ();
                     if((rollnum=pop(&unusedRoll))!=-1)
                        insert(rollnum,name_data[num-1],dtob[num-1],address[num-1],phone[num-1]);
                     else
                        printf("linked list in full\n");
                     printf("operation completed\n");
                     end = clock();
                     cpu_time = ((double) (end - start)) / CLOCKS_PER_SEC;
                     printf("cpu time used %f", cpu_time);
                     break;
             case 2:
                     printf("operation delete\n");
                     printf("enter roll to delete\n") ;
                     int rolln;
                     scanf("%d",&rolln);
                     while ((getchar()) != '\n');
                     start = clock ();
                     delete(rolln,&unusedRoll);
                     printf("operation completed\n");
                     end = clock();
                     cpu_time = ((double) (end - start)) / CLOCKS_PER_SEC;
                     printf("cpu time used %f", cpu_time);
                     break;
             case 3:
                     printf("operation search\n");
                     printf("enter roll number to search for:\n");
                     int rollnumber;
                     scanf("%d",&rollnumber);
                     while ((getchar()) != '\n');
                     start = clock ();
                     search(rollnumber);
                     printf("operation completed");
                     end = clock();
                     cpu_time = ((double) (end - start)) / CLOCKS_PER_SEC;
                     printf("cpu time used %f", cpu_time);
                     break;
             case 4:
                     printf("operation modify");
                     int num_in;
                     scanf("%d",&num_in);
                     while ((getchar()) != '\n');
                     start = clock ();
                     modify(num_in);
                     printf("operation completed");
                     end = clock();
                     cpu_time = ((double) (end - start)) / CLOCKS_PER_SEC;
                     printf("cpu time used %f", cpu_time);
                     break;
             case 5:
                     printf("operation sort by name");
                     start = clock ();
                     sortByName();
                     printf("operation completed");
                     end = clock();
                     cpu_time = ((double) (end - start)) / CLOCKS_PER_SEC;
                     printf("cpu time used %f", cpu_time);
                     break;
             case 6:
                     printf("operation print");
                     start = clock ();
                     printList();
                     printf("operation completed");
                     end = clock();
                     cpu_time = ((double) (end - start)) / CLOCKS_PER_SEC;
                     printf("cpu time used %f", cpu_time);
                     break;
             default: printf("wrong choice");
         }
         if(op==-1)
         break;
     }
 }
References init_queue(), insert(), modify(), pop(), printList(), push(), search(), and sortByName().
Variable Documentation
first
node* first = NULL
Definition at line 71 of file PS-1.c.
Referenced by delete(), insert(), modify(), printList(), search(), sortByName(), and sortByRollNumber().
last
node * last = NULL
Definition at line 71 of file PS-1.c.
Referenced by delete(), insert(), and printList().
size
int size = 0
Definition at line 72 of file PS-1.c.
Referenced by search_queue().